# Generated by Django 5.2 on 2025-04-12 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
