# Generated by Django 5.2 on 2025-04-16 00:30

from django.db import migrations
from django.db.models import F
from decimal import Decimal

def populate_salary_reports(apps, schema_editor):
    SalaryReport = apps.get_model('teachers_app', 'SalaryReport')
    WorkSession = apps.get_model('teachers_app', 'WorkSession')
    
    # Get all salary reports that need to be populated
    reports = SalaryReport.objects.filter(
        total_hours__isnull=True,
        total_amount__isnull=True
    )
    
    for report in reports:
        # Get all work sessions for this report
        work_sessions = WorkSession.objects.filter(
            teacher=report.teacher,
            created_at__gte=report.start_date,
            created_at__lt=report.end_date
        )
        
        # Calculate total hours and amount
        total_hours = Decimal(0)
        total_amount = Decimal(0)
        
        for session in work_sessions:
            # Calculate hours based on entry type
            hours = Decimal(0)
            if session.entry_type == 'manual' and session.manual_hours:
                hours = session.manual_hours
            elif session.entry_type == 'clock' and session.clock_in and session.clock_out:
                duration = session.clock_out - session.clock_in
                hours = Decimal(str(duration.total_seconds() / 3600))
            elif session.entry_type == 'time_range' and session.start_time and session.end_time:
                duration = session.end_time - session.start_time
                hours = Decimal(str(duration.total_seconds() / 3600))
            
            total_hours += hours
            total_amount += session.total_amount
        
        # Update the report with calculated values
        report.total_hours = total_hours
        report.total_amount = total_amount
        report.save()

    print(f"Updated {reports.count()} salary reports with historical data")

class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0002_salaryreport_deleted_at_salaryreport_is_deleted_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_salary_reports),
    ]
