# Generated by Django 5.1.6 on 2025-04-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0002_task_remove_teacher_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.CharField(blank=True, help_text='Optional: List of subjects taught', max_length=200),
        ),
    ]
