# Generated by Django 5.2 on 2025-04-16 00:48

from django.db import migrations
from django.db.models import DecimalField

class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0003_populate_salary_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='hourly_rate',
            field=DecimalField(max_digits=10, decimal_places=2, null=True, blank=True),
        ),
    ]
