# Generated by Django 5.2 on 2025-04-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0003_teacher_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='entry_type',
            field=models.CharField(choices=[('manual', 'Manual Hours Input'), ('clock', 'Clock In/Out'), ('time_range', 'Time Range')], max_length=10),
        ),
    ]
