# Generated by Django 5.2 on 2025-04-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0002_alter_customuser_managers'),
        ('teachers_app', '0004_worksession_end_time_worksession_start_time_and_more'),
    ]

    operations = [
    ]
