# Generated by Django 5.2 on 2025-04-16 00:48

from django.db import migrations
from decimal import Decimal

def populate_hourly_rates(apps, schema_editor):
    WorkSession = apps.get_model('teachers_app', 'WorkSession')
    Task = apps.get_model('teachers_app', 'Task')
    
    # Get all work sessions that need hourly rate populated
    sessions = WorkSession.objects.filter(hourly_rate=None)
    
    for session in sessions:
        # Get the hourly rate from the associated task
        if session.task:
            session.hourly_rate = session.task.hourly_rate
            session.save()
    
    print(f"Updated {sessions.count()} work sessions with hourly rates")

class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0004_add_hourly_rate_field'),
    ]

    operations = [
        migrations.RunPython(populate_hourly_rates),
    ]
