# Generated by Django 5.2 on 2025-04-18 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0004_studentprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
