# Generated by Django 5.2 on 2025-04-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0005_populate_hourly_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksession',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
