# Generated by Django 5.2 on 2025-04-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0006_worksession_deleted_at_worksession_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='stored_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
