# Generated by Django 5.1.6 on 2025-04-24 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0007_bill_billitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers_app.student'),
        ),
    ]
