# Generated by Django 5.2 on 2025-04-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0008_salaryreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryreport',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='salaryreport',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
