# Generated by Django 5.1.6 on 2025-04-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0008_worksession_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='service_price_at_billing',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
