# Generated by Django 5.2 on 2025-04-13 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0009_salaryreport_month_salaryreport_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryreport',
            name='month',
        ),
        migrations.RemoveField(
            model_name='salaryreport',
            name='total_salary',
        ),
        migrations.RemoveField(
            model_name='salaryreport',
            name='year',
        ),
    ]
